name: Rust

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: codeberg-tiny

    steps:
    - uses: actions/checkout@v3

    # Run on Stable until someone wants us to target something else
    - uses: dtolnay/rust-toolchain@stable
    
    - name: Run CI checks
      run: just ci
